export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  USERS: "/users",
  TENANTS: "/tenants",
  MENU: "/menu",
  PRODUCTS: "/products",
  CREATE_PRODUCT: "/products/create",
  PRODUCT_DETAIL: "/products/:productId",
  CATEGORIES: "/categories",
  TOPPINGS: "/toppings",
  CREATE_TOPPING: "/toppings/create",
  TOPPING_DETAIL: "/toppings/:toppingId",
  ORDERS: "/orders",
  ORDER_DETAIL: "/orders/:orderId",
  SALES: "/sales",
  PROMOS: "/promos",
  SETTINGS: "/settings",
  HELP: "/help",
  NOT_FOUND: "*",
} as const;

export type RouteKey = keyof typeof ROUTES;
