import { DashboardLayout } from "../components/layout/DashboardLayout";
import { Card, Table, Tag, Button, Input, Space, Modal, message, Dropdown } from "antd";
import {
  SearchOutlined,
  PlusOutlined,
  MoreOutlined,
  EditOutlined,
  DeleteOutlined,
  EyeOutlined,
} from "@ant-design/icons";
import { useState, useEffect } from "react";
import type { ColumnType } from "antd/es/table";
import type { MenuProps } from "antd";
import { useCategories } from "../modules/categories/hooks/useCategories";
import type { Category, PriceConfiguration } from "../modules/categories/api/types";
import dayjs from "dayjs";
import { useAppSelector } from "../app/hooks";
import { useTenants } from "../modules/tenants/hooks/useTenants";
import { CategoryDrawer, type CategoryFormValues } from "../components/categories/CategoryDrawer";

interface CategoryTableData extends Category {
  key: string;
}

export const CategoriesPage = () => {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [editingCategory, setEditingCategory] = useState<CategoryTableData | null>(null);
  const [isViewModalOpen, setIsViewModalOpen] = useState(false);

  // Get current user from Redux
  const { user } = useAppSelector((state) => state.login);
  const isAdmin = user?.role === "admin";

  const {
    categories,
    selectedCategory,
    loading,
    error,
    currentPage,
    pageSize,
    total,
    searchQuery,
    loadCategories,
    loadCategoryById,
    handleCreateCategory,
    handleUpdateCategory,
    handleDeleteCategory,
    handleSearchChange,
    handlePageChange,
    clearCategory,
  } = useCategories();

  // Fetch tenants for admin dropdown
  const { tenants, loadTenants } = useTenants();

  useEffect(() => {
    loadCategories();
    if (isAdmin) {
      loadTenants();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isAdmin]);

  const handleEdit = (category: CategoryTableData) => {
    setEditingCategory(category);
    setIsDrawerOpen(true);
  };

  const handleView = async (category: CategoryTableData) => {
    await loadCategoryById(category._id);
    setIsViewModalOpen(true);
  };

  const handleDelete = (category: CategoryTableData) => {
    Modal.confirm({
      title: "Delete Category",
      content: `Are you sure you want to delete "${category.name}"? This action cannot be undone.`,
      okText: "Delete",
      okType: "danger",
      cancelText: "Cancel",
      async onOk() {
        await handleDeleteCategory(category._id);
      },
    });
  };

  const getActionMenu = (record: CategoryTableData): MenuProps => ({
    items: [
      {
        key: "view",
        icon: <EyeOutlined />,
        label: "View",
        onClick: () => handleView(record),
      },
      {
        key: "edit",
        icon: <EditOutlined />,
        label: "Edit",
        onClick: () => handleEdit(record),
      },
      {
        key: "delete",
        icon: <DeleteOutlined />,
        label: "Delete",
        danger: true,
        onClick: () => handleDelete(record),
      },
    ],
  });

  const columns: ColumnType<CategoryTableData>[] = [
    {
      title: "Category name",
      dataIndex: "name",
      key: "name",
    },
    {
      title: "Status",
      dataIndex: "isPublished",
      key: "isPublished",
      render: (isPublished?: boolean) => (
        <Tag color={isPublished !== false ? "green" : "default"}>
          {isPublished !== false ? "Published" : "Draft"}
        </Tag>
      ),
    },
    {
      title: "Created at",
      dataIndex: "createdAt",
      key: "createdAt",
      render: (date: string) => dayjs(date).format("DD MMMM YYYY"),
    },
    {
      title: "Actions",
      key: "actions",
      width: 80,
      render: (_, record) => (
        <Dropdown menu={getActionMenu(record)} trigger={["click"]}>
          <Button type="text" icon={<MoreOutlined />} />
        </Dropdown>
      ),
    },
  ];

  const tableData: CategoryTableData[] = categories.map((category) => ({
    ...category,
    key: category._id,
  }));

  const handleDrawerSubmit = async (values: CategoryFormValues) => {
    try {
      // Transform form values to API format
      const priceCofigration: PriceConfiguration = {};
      values.priceConfigurations.forEach((config) => {
        priceCofigration[config.name] = {
          priceType: config.priceType,
          availableOptions: config.availableOptions,
          _id: "", // Will be generated by backend
        };
      });

      const attributes = values.attributes.map((attr) => ({
        name: attr.name,
        wigetType: attr.widgetType,
        defaultValue: attr.defaultValue,
        availableOptions: attr.availableOptions,
      }));

      if (editingCategory) {
        await handleUpdateCategory(editingCategory._id, {
          name: values.name,
          priceCofigration,
          attributes,
        });
      } else {
        await handleCreateCategory({
          name: values.name,
          priceCofigration,
          attributes,
          ...(isAdmin && values.tenantId && { tenantId: values.tenantId }),
        });
      }

      setEditingCategory(null);
      setIsDrawerOpen(false);
    } catch (error) {
      console.error("Error saving category:", error);
    }
  };

  const handleDrawerClose = () => {
    setEditingCategory(null);
    setIsDrawerOpen(false);
  };

  const handleCreateNew = () => {
    setEditingCategory(null);
    setIsDrawerOpen(true);
  };

  useEffect(() => {
    if (error) {
      message.error(error);
    }
  }, [error]);

  return (
    <DashboardLayout>
      <Card
        style={{ borderRadius: "12px" }}
        title={<span style={{ fontSize: "20px", fontWeight: "600" }}>Categories</span>}
        extra={
          <Space>
            <Input
              placeholder="Search categories..."
              prefix={<SearchOutlined />}
              style={{ width: 200 }}
              value={searchQuery}
              onChange={(e) => {
                const newSearchValue = e.target.value;
                handleSearchChange(newSearchValue);
                loadCategories(1, pageSize, newSearchValue);
              }}
              allowClear
            />
            <Button
              type="primary"
              icon={<PlusOutlined />}
              style={{ background: "#ff4d4f" }}
              onClick={handleCreateNew}
            >
              Create Category
            </Button>
          </Space>
        }
      >
        <Table
          columns={columns}
          dataSource={tableData}
          loading={loading}
          pagination={{
            current: currentPage,
            pageSize: pageSize,
            total: total,
            showSizeChanger: false,
            onChange: handlePageChange,
          }}
        />
      </Card>

      <CategoryDrawer
        open={isDrawerOpen}
        onClose={handleDrawerClose}
        onSubmit={handleDrawerSubmit}
        isAdmin={isAdmin}
        tenants={tenants}
        editingCategory={editingCategory}
      />

      <Modal
        title="Category Details"
        open={isViewModalOpen}
        onCancel={() => {
          setIsViewModalOpen(false);
          clearCategory();
        }}
        footer={[
          <Button
            key="close"
            onClick={() => {
              setIsViewModalOpen(false);
              clearCategory();
            }}
          >
            Close
          </Button>,
        ]}
        width={800}
      >
        {selectedCategory && (
          <div style={{ maxHeight: "600px", overflowY: "auto" }}>
            {/* Basic Info */}
            <Card size="small" style={{ marginBottom: "16px" }}>
              <h3 style={{ fontSize: "16px", fontWeight: "600", marginBottom: "12px" }}>
                Basic Information
              </h3>
              <Space direction="vertical" style={{ width: "100%" }}>
                <div>
                  <strong>ID:</strong> <span style={{ color: "#666" }}>{selectedCategory._id}</span>
                </div>
                <div>
                  <strong>Name:</strong>{" "}
                  <span style={{ color: "#666" }}>{selectedCategory.name}</span>
                </div>
                <div>
                  <strong>Tenant ID:</strong>{" "}
                  <span style={{ color: "#666" }}>{selectedCategory.tenantId}</span>
                </div>
                <div>
                  <strong>Status:</strong>{" "}
                  <Tag color={selectedCategory.isPublished !== false ? "green" : "default"}>
                    {selectedCategory.isPublished !== false ? "Published" : "Draft"}
                  </Tag>
                </div>
                {selectedCategory.createdAt && (
                  <div>
                    <strong>Created:</strong>{" "}
                    <span style={{ color: "#666" }}>
                      {dayjs(selectedCategory.createdAt).format("DD MMMM YYYY, HH:mm")}
                    </span>
                  </div>
                )}
              </Space>
            </Card>

            {/* Price Configuration */}
            <Card size="small" style={{ marginBottom: "16px" }}>
              <h3 style={{ fontSize: "16px", fontWeight: "600", marginBottom: "12px" }}>
                Price Configuration
              </h3>
              {Object.entries(selectedCategory.priceCofigration).map(([key, config]) => (
                <Card
                  key={key}
                  type="inner"
                  size="small"
                  title={key.charAt(0).toUpperCase() + key.slice(1)}
                  style={{ marginBottom: "8px" }}
                >
                  <Space direction="vertical" style={{ width: "100%" }}>
                    <div>
                      <strong>Price Type:</strong>{" "}
                      <Tag color={config.priceType === "base" ? "blue" : "orange"}>
                        {config.priceType === "base" ? "Base Price" : "Additional Price"}
                      </Tag>
                    </div>
                    <div>
                      <strong>Available Options:</strong>
                      <div style={{ marginTop: "8px" }}>
                        {config.availableOptions.map((option: string, idx: number) => (
                          <Tag key={idx} color="default" style={{ marginBottom: "4px" }}>
                            {option}
                          </Tag>
                        ))}
                      </div>
                    </div>
                  </Space>
                </Card>
              ))}
            </Card>

            {/* Attributes */}
            {selectedCategory.attributes && selectedCategory.attributes.length > 0 && (
              <Card size="small">
                <h3 style={{ fontSize: "16px", fontWeight: "600", marginBottom: "12px" }}>
                  Attributes
                </h3>
                {selectedCategory.attributes.map((attr) => (
                  <Card
                    key={attr._id}
                    type="inner"
                    size="small"
                    title={attr.name}
                    style={{ marginBottom: "8px" }}
                  >
                    <Space direction="vertical" style={{ width: "100%" }}>
                      <div>
                        <strong>Widget Type:</strong> <Tag color="purple">{attr.wigetType}</Tag>
                      </div>
                      <div>
                        <strong>Default Value:</strong>{" "}
                        <span style={{ color: "#666" }}>{attr.defaultValue}</span>
                      </div>
                      <div>
                        <strong>Available Options:</strong>
                        <div style={{ marginTop: "8px" }}>
                          {attr.availableOptions.map((option: string, idx: number) => (
                            <Tag key={idx} color="default" style={{ marginBottom: "4px" }}>
                              {option}
                            </Tag>
                          ))}
                        </div>
                      </div>
                    </Space>
                  </Card>
                ))}
              </Card>
            )}
          </div>
        )}
      </Modal>
    </DashboardLayout>
  );
};
